#!/usr/bin/env perl

use FindBin;
use lib "$FindBin::Bin/";

use Dancer2;
use rpmmon_control;

get '/rpmmon' => sub {
	template 'rpmmon';
};


#Initialize Databases. Set new starting point. 
get '/init' => sub {
	rpmmon_control::get_current_rpms(1);
	return "<br>RPM Database initialised... Please wait for the site to reload...<br>";
};


# Get actual installed RPMs and build difference to starting point.
get '/view' => sub {
	my ($rpm_counter, $new_on_system, $deleted_on_system) = rpmmon_control::get_changes();
	template 'view', { count=>$rpm_counter, new_rpm=>$new_on_system, old_rpm=>$deleted_on_system };
};

#And start dancing...
dance;
